---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending
      - id: no-commit-to-branch
  - repo: local
    hooks:
      - id: go-fix
        name: go fix
        entry: go fix ./...
        language: system
        pass_filenames: false
        files: 'go.mod'
      - id: go-generate
        name: go generate
        entry: go generate ./...
        language: system
        pass_filenames: false
      - id: go-fmt
        name: go fmt
        entry: gofmt -w
        language: system
        types: [go]
      - id: go-mod-tidy
        name: go mod tidy
        entry: go mod tidy
        language: system
        pass_filenames: false
        files: 'go.mod'
      - id: go-test
        name: go test
        entry: go test ./...
        language: system
        pass_filenames: false
      - id: go-vet
        name: go vet
        entry: go vet ./...
        language: system
        pass_filenames: false
        types: [go]
exclude: ^.github/.*$
